# Generated by Django 5.1 on 2024-08-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('comments', '0001_initial'),
        ('halls', '0001_initial'),
        ('movies', '0003_alter_movie_user'),
        ('ratings', '0001_initial'),
        ('reviews', '0001_initial'),
        ('showtimes', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='movies', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='movies', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='movie',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='halls.hall'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='movies', to='ratings.rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='movies', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='movie',
            name='showtimes',
            field=models.ManyToManyField(blank=True, related_name='movies', to='showtimes.showtime'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='tags.tag'),
        ),
    ]
