# Generated by Django 5.1 on 2024-08-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movielike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieLike',
        ),
    ]
