# Generated by Django 5.1 on 2024-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
