# Generated by Django 5.1 on 2024-08-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_progress_videoprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProgress',
        ),
    ]
