# Generated by Django 5.1 on 2024-08-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_file_movie_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
    ]
