# Generated by Django 5.1 on 2024-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_movie_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitles',
            field=models.FileField(blank=True, null=True, upload_to='movies/subtitles/'),
        ),
    ]
