# Generated by Django 5.1 on 2024-08-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_movie_language_movie_subtitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subtitles',
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='movies/subtitles/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.movie')),
            ],
        ),
    ]
