# Generated by Django 5.1 on 2024-08-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
