# Generated by Django 5.1 on 2024-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='capacity',
            new_name='rows',
        ),
        migrations.AddField(
            model_name='hall',
            name='seats_in_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
