# Generated by Django 5.1 on 2024-08-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_alter_hall_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='name',
        ),
    ]
