# Generated by Django 5.1 on 2024-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_remove_hall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
